### PR TITLE
fix overflow of integer types when writing large unsigned long longs …

### PR DESCRIPTION
**Pull request by iamleeg**
…to JSON. This is a fix for #12.

### CODE REVIEW

**Comment by zneak** [comment]
I did mess up the original problem description: numbers were always treated as signed, not unsigned.

I don't know what your test was like, but it could be as simple as:

* JSON-serializing `[NSNumber numberWithUnsignedLongLong:0xffffffffffffffff]` and checking that it's equal to `@"18446744073709551615"`
* JSON-serializing `[NSNumber numberWithLongLong:0xffffffffffffffff]` and checking that it's equal to  `@"-1"`

**Comment by iamleeg** [comment]
my test was doing a round-trip (so writing the number to JSON, reading the JSON back and checking the number), which doesn't work because numbers are scanned as `double`. Your test suggestion should be easy to build :).

**Comment by davidchisnall** [comment]
Looks good to me, but the ChangeLog entry needs a merge from master to avoid the conflict.

Please also add this to the commit message:

Fixes #12

**Comment by davidchisnall** [comment]
Looks fine.  I'll merge once Travis finishes testing.

**Pull request merged**
