### PR TITLE
NotificationCenter removeObserver

### PR DESCRIPTION
**Pull request by williameveretteggplant**
This modifies the NotificationCenter class to do the following:
  - add an ivar to the class for an array to hold observers that need to be released when they are removed
  - adds an observer to that array if the observer is of class GSNotificationObserver
  - upon removing an observer, check if it is in that array, if so remove it from the array and release it.
 
This replaces the previous implementation which checked the class of the observer as it was being removed, which would cause a crash if the observer had been deallocated.

### CODE REVIEW

**Comment by qmfrederik** [comment]
The MinGW GCC build errors are weird.  I assume it's because you are using an iterator in your code.  What happens if you change:

```objc
  for (id listObserver in _retainedObserverArray) 
    {
      if (listObserver == observer)
        {
	  needToRelease = YES;
          break;
	}
    }
```

to

```objc
for (int i = 0; i < [cs count]; i++)
  {
     if ([_retainedObserverArray objectAtIndex: i] == observer)
       {
	  needToRelease = YES;
          break;
       }
  }
```

or just

```objc
if ([_retainedObserverArray containsObject:observer)
  {
    needToRelease = YES;
    break;
  }
```

?

**Comment by rfm** [comment]
The best code for NSArray would use the -indexOfObjectIdenticalTo: since (as well as being a portable alternative) this is simpler and more efficient than the use if fast enumeration.

I'm not completely sure that holding the observer in a mutable array is the best approach though; an array is efficient if there are a small number of observers, but doesn't scale well if there are a lot of observers being added and removed.  To scale, the function API of NSHashTable API (or using the GSI macros) would probably be fastest.

**Review by rfm — COMMENTED** [review]
It occurs to me that it would be better to add the new collection to the table rather than as a direct ivar of NSNotification (to hide it).

**Comment by williameveretteggplant** [comment]
I have taken suggestions into account and updated.

**Review by rfm — APPROVED** [review]
That all looks workable.

**Pull request merged**
