### PR TITLE
Fix time zone lookup on Windows MSVC when using non-English locale

### PR DESCRIPTION
**Pull request by triplef**
Fixes the conversion of Windows time zone names to IANA names introduced in #232 on systems not using an English locale, and adds a warning when [`ucal_getTimeZoneIDForWindowsID`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucal_8h.html#ac345a8561828554c092663e541b1c7bd) is unable to map the time zone (in which case it’s documented to return success but a zero length string).

### CODE REVIEW

**Review by rfm — COMMENTED** [review]
Reading around this, the changes all look fine.  However, I wonder if making them conditional on _MSC_VER is necessary;  would they not work whether that define is present or not?

**Comment by triplef** [comment]
I didn’t try this but I thought maybe MinGW behaves more like Unixes and already return IANA time zone names in the first place. At least all the NSTimeZone tests are passing on MinGW so I didn’t want to change anything on that platform. It would probably be worth checking that though.

**Comment by hmelder** [comment]
On MinGW the standard IANA format is used. tzdata is a MinGW core dependency, as seen in the screenshot.

tzdata: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-tzdata/PKGBUILD

image

**Comment by triplef** [comment]
Thanks for checking @hmelder!

**Pull request merged**
