### PR TITLE
win32: Support overlapped (asynchronous) I/O on standard streams in GSFileHandle

### PR DESCRIPTION
**Pull request by hmelder**

### CODE REVIEW

**Comment by hmelder** [comment]
It seems like win32/GSFileHandle uses tabs instead of spaces for indentation.

**Comment by hmelder** [comment]
Should I retab it or use tabs for indentation? @rfm

**Comment by rfm** [comment]
I think it's better to standardise on spaces.

**Comment by hmelder** [comment]
> I think it's better to standardise on spaces.

Should I convert the complete source file to spaces?

**Comment by rfm** [comment]
> Should I convert the complete source file to spaces?

I had a look at the file and can see that it's all correctly indented.   It's not indented with tabs.  It uses tabs and spaces with tabstops at the conventional 8 space intervals, so it doesn't really need any changes to work in decent code editors (with fixed width fonts).
However, using spaces exclusively will do no harm.

**Comment by triplef** [comment]
> It's not indented with tabs. It uses tabs and spaces with tabstops at the conventional 8 space intervals

FWIW I’m always struggling to configure my editors to deal with this combination of tabs and spaces, which I’ve also never seen in any other project. Would be great if going forward we could use spaces exclusively to keep things simple.

**Comment by rfm** [comment]
I don't see a problem with using all spaces.

**Comment by hmelder** [comment]
Adjusted the indentation @rfm

**Review by rfm — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
