### PR TITLE
Skip all NSURL* test cases using GSInetServerStream on Windows

### PR DESCRIPTION
**Pull request by hmelder**

### CODE REVIEW

**Comment by hmelder** [comment]
Btw I think we should deprecate GSServerStream. It is not using anywhere in our code base and only exposed as a category in GNUstep additions. The implementation is too complicated for what it does.

**Comment by hmelder** [comment]
Is it ok to merge @rfm ?

**Comment by rfm** [comment]
I'm not sure of the rationale here.
While GSServerStream is (so far as i can see) only used in NSSetServices in the base library and in a few testcases, I wonder if it's really not useful / too complicated?  I think it would be fine to deprecate and then replace it in those places (and remove it from the additions api)  if it's easy.
But, if it's simple to replace, why not do that rather than removing the tests?

**Comment by hmelder** [comment]
>> But, if it's simple to replace, why not do that rather than removing the tests?
The unit tests implement multiple test server based on GSServerStream. Rewriting all of them would be a major undertaking. I think we should temporarily disable them.

**Comment by triplef** [comment]
#266 has some more info about the issues with GSServerStream on Windows.

For now it would be great if we can mark the tests using it as hopeful on Windows (as this PR does). This will allow us to disable `allow-test-failures` on the Windows CI targets, so that possible future changes breaking Windows builds will actually fail those builds.

**Comment by rfm** [comment]
Marking the tests as hopeful seems fine to me.

**Comment by hmelder** [comment]
> Marking the tests as hopeful seems fine to me.

This was my original plan, but I ran into some issues back then. I can look into this and update the PR.

**Comment by hmelder** [comment]
Forgot the semicolons. Wrote to much golang :)

**Comment by hmelder** [comment]
Done! We have no test failures in Windows MinGW GCC x86_64 and Windows MSVC x86_64. There is still an unrelated test failure on 32-bit machines. Ready to check @rfm

**Comment by triplef** [comment]
Awesome, great job @hmelder! 🎉

I think this should be removed then as well (for both 64-bit Windows targets):
https://github.com/gnustep/libs-base/blob/996a5b8a841c15ac6592cdb654ed2655d6c5ee3d/.github/workflows/main.yml#L67

**Comment by hmelder** [comment]
@rfm ready to review

**Comment by RoyalStewart90** [comment]
Hi @hmelder, very sorry to be this late to the party, earlier this year I was poking around the IPv6 functionality and made some changes to my company's branch of Master. In your experience, what was the issue with GSInetServerStream? I had encountered a few issues of formatting IPv6 address with brackets related to GSStreams. The biggest issue I ran into was memory allocation of IP addresses. I'm hoping at some point we can get this issue fixed and re-enable more connection tests.

**Comment by hmelder** [comment]
@RoyalStewart90 see #266

I think it was an issue with the asynchronous event handling on Windows. I would have to go into the issue as this was about a year ago :)

**Pull request merged**
