### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by gcasa**
Add documentation to different classes.

### CODE REVIEW

**Review by fredkiefer — APPROVED** [review]
Not sure, should there be an empty line at the end of the second file?

**Comment by gcasa** [comment]
> Not sure, should there be an empty line at the end of the second file?

No, why am I getting the above failures?  I am presuming this is not due to this change.

**Review by rfm — APPROVED** [review]
I'm not sure if the intention was to document all methods (not all are), but this seems to be a good improvement anyway.

**Comment by gcasa** [comment]
> I'm not sure if the intention was to document all methods (not all are), but this seems to be a good improvement anyway.

I'm not done.  I am finishing up now.

**Comment by rfm** [comment]
Sorry I already merged.
  

  

  

  
  
  
  
  
>

**Comment by gcasa** [comment]
No worries.  Just a few minor things to add and I'll just do a direct merge.  Thanks.

**Comment by gcasa** [comment]
Did a quick fix for the rest.  Thanks again.

**Pull request merged**
