### PR TITLE
debug test failure

### PR DESCRIPTION
**Pull request by levinli303**

### CODE REVIEW

**Comment by fredkiefer** [comment]
You could speed up the tests by editing the file `.github/workflows/main.yml`

**Comment by levinli303** [comment]
@fredkiefer  looks like an exception is thrown: ./obj/test01: Uncaught exception NSInvalidArgumentException, reason: [GSPlaceholderString-initWithUTF8String:]: NULL cString
NSInvalidArgumentException: <NSException: 0x56163854cbc0> NAME:NSInvalidArgumentException REASON:[GSPlaceholderString-initWithUTF8String:]: NULL cString INFO:(null)Failed file:     test01.m aborted without running all tests!

**Comment by fredkiefer** [comment]
Sorry, I am having trouble to follow the test. In test6 you showed that six additions and one removal cause problems. From me the next logical step would have been to eliminate the removal, but I am not sure whether any of the following tests shows that. Starting from test6 I am really confused what you are trying to achieve.

**Comment by levinli303** [comment]
I thought some specific entry in Localizable.strings is causing CI to fail. And I was able to find a good change narrowing down the bad entries to the following ones. I cannot do a binary search since there appears to be multiple bad entries.

test 1 ~ 5 only adding one of the five below

```
NSWindowsLatin1StringEncoding =     "Western (Windows Latin 1)";
NSWindowsLatin2StringEncoding =     "Central European (Windows Latin 2)";
NSWindowsCyrillicStringEncoding =     "Cyrillic (Windows)";
NSWindowsGreekStringEncoding =     "Greek (Windows)";
NSWindowsLatin5StringEncoding =     "Turkish (Windows Latin 5)";
```

test 6~10, adding 5/6 of the ones below trying to find the group containing bad ones.

```
NSMacOSJapaneseStringEncoding =     "Japanese (Mac OS)";
 NSMacOSTraditionalChineseStringEncoding =     "Traditional Chinese (Mac OS)";
 NSMacOSKoreanStringEncoding =     "Korean (Mac OS)";
 NSMacOSArabicStringEncoding =     "Arabic (Mac OS)";
 NSMacOSHebrewStringEncoding =     "Hebrew (Mac OS)";
 NSMacOSGreekStringEncoding =     "Greek (Mac OS)";
 NSMacOSCyrillicStringEncoding =     "Cyrillic (Mac OS)";
 NSMacOSDevanagariStringEncoding =     "Devanagari (Mac OS)";
 NSMacOSGurmukhiStringEncoding =     "Gurmukhi (Mac OS)";
 NSMacOSGujaratiStringEncoding =     "Gujarati (Mac OS)";
 NSMacOSOriyaStringEncoding =     "Oriya (Mac OS)";
 NSMacOSBengaliStringEncoding =     "Bengali (Mac OS)";
 NSMacOSTamilStringEncoding =     "Tamil (Mac OS)";
 NSMacOSTeluguStringEncoding =     "Telugu (Mac OS)";
 NSMacOSKannadaStringEncoding =     "Kannada (Mac OS)";
 NSMacOSMalayalamStringEncoding =     "Malayalam (Mac OS)";
 NSMacOSSinhaleseStringEncoding =     "Sinhalese (Mac OS)";
 NSMacOSBurmeseStringEncoding =     "Burmese (Mac OS)";
 NSMacOSKhmerStringEncoding =     "Khmer (Mac OS)";
 NSMacOSThaiStringEncoding =     "Thai (Mac OS)";
 NSMacOSLaotianStringEncoding =     "Laotian (Mac OS)";
 NSMacOSGeorgianStringEncoding =     "Georgian (Mac OS)";
 NSMacOSArmenianStringEncoding =     "Armenian (Mac OS)";
 NSMacOSSimplifiedChineseStringEncoding =     "Simplified Chinese (Mac OS)";
 NSMacOSTibetanStringEncoding =     "Tibetan (Mac OS)";
 NSMacOSMongolianStringEncoding =     "Mongolian (Mac OS)";
 NSMacOSEthiopicStringEncoding =     "Ethiopic (Mac OS)";
 NSMacOSCentralEuropeanRomanStringEncoding =     "Central European (Mac OS)";
 NSMacOSVietnameseStringEncoding =     "Vietnamese (Mac OS)";
```

but the result is very weird, you can see test 1 ~ test 5 all passed individually. but if I added all together in `bad string 1~5 combined` it failed.

**Pull request closed without merging**
